# Gradle runtime options
org.gradle.daemon = true
org.gradle.jvmargs = -Xmx3G
org.gradle.parallel = true
org.gradle.caching = true

# Java / Hytale options
java_version = 25
hytale_version = 0.+

# Mod identity
group = com.nopefr.blockregen
manifest_group = com.nopefr
mod_name = BlockRegen
main_class = com.nopefr.blockregen.BlockRegenPlugin
mod_author = NopeFR
mod_id = BlockRegen
mod_license = MIT
mod_description = Automatically regenerates a block type after a configurable delay.
mod_url =
version = 1.2.0

# Manifest / packaging options
includes_pack = true
disabled_by_default = false
patchline = release
server_version = 0.6.3
manifestServerVersion = >=0.6.3 <0.7.0
manifest_dependencies =
manifest_opt_dependencies =
curseforgeID =
injectServerJavadocsIntoSources = true
generateAssetsBinary = false
